// Exercises added by GreenCoach on top of free-exercise-db (original text, released with this project).
// [id, EN name, JA name, primary, secondary, equipment, pattern, mechanic, difficulty, fatigue, EN steps, JA steps, joint notes]
const rows = [
  ["x-bulgarian-split-squat", "Bulgarian Split Squat", "ブルガリアンスクワット", ["quadriceps"], ["glutes", "adductors"], ["dumbbell", "bench"], "lunge", "c", 2, 4,
    ["Stand facing away from a bench and rest the top of one foot on it.", "Hold dumbbells at your sides and step the front foot far enough forward that the shin stays near vertical at the bottom.", "Lower straight down until the front thigh is about parallel to the floor.", "Drive through the whole front foot to stand up. Finish all reps, then switch legs."],
    ["ベンチに背を向けて立ち、片足の甲をベンチに乗せます。", "ダンベルを両手に持ち、下げたときにすねがほぼ垂直になる位置まで前足を踏み出します。", "前の太ももが床と平行になるまで真下にしゃがみます。", "前足全体で床を押して立ち上がります。規定回数を終えたら脚を替えます。"], ["knee"]],
  ["x-dumbbell-romanian-deadlift", "Dumbbell Romanian Deadlift", "ダンベルルーマニアンデッドリフト", ["hamstrings"], ["glutes", "lower-back"], ["dumbbell"], "hinge", "c", 1, 3,
    ["Stand holding dumbbells in front of your thighs with a soft bend in the knees.", "Push your hips back and slide the dumbbells down your thighs, keeping your back flat.", "Stop when you feel a strong stretch in the hamstrings, usually just below the knees.", "Squeeze your glutes and drive the hips forward to stand tall."],
    ["太ももの前でダンベルを持ち、膝を軽く曲げて立ちます。", "背中を平らに保ったまま、お尻を後ろに引きながらダンベルを太ももに沿って下ろします。", "ハムストリングが強く伸びるところ（膝のすぐ下あたり）で止めます。", "お尻を締め、股関節を前に押し出して立ち上がります。"], ["lower-back"]],
  ["x-pendlay-row", "Pendlay Row", "ペンドレイロウ", ["middle-back"], ["lats", "lower-back", "biceps"], ["barbell"], "h-pull", "c", 3, 4,
    ["Set the barbell on the floor and hinge over with a flat back, torso close to parallel to the floor.", "Grip the bar slightly wider than shoulder width.", "Explosively row the bar to your lower chest while keeping your torso still.", "Lower the bar back to the floor under control and reset before each rep."],
    ["バーベルを床に置き、背中を平らにして上体が床とほぼ平行になるまで前傾します。", "肩幅よりやや広くバーを握ります。", "上体を動かさずに、バーを素早く下胸まで引き上げます。", "バーをコントロールして床に戻し、毎回セットし直します。"], ["lower-back"]],
  ["x-chest-supported-row", "Chest-Supported Dumbbell Row", "チェストサポート・ダンベルロウ", ["middle-back"], ["lats", "biceps", "shoulders"], ["dumbbell", "bench"], "h-pull", "c", 1, 2,
    ["Set a bench at about 30-45 degrees and lie face down on it with a dumbbell in each hand.", "Let your arms hang straight down with the shoulder blades relaxed forward.", "Row the dumbbells toward your hips, squeezing the shoulder blades together.", "Lower slowly until your arms are fully extended."],
    ["ベンチを30〜45度に設定し、ダンベルを両手に持ってうつ伏せになります。", "腕をまっすぐ下に垂らし、肩甲骨を軽く前に開きます。", "肩甲骨を寄せながら、ダンベルを腰に向けて引きます。", "腕が完全に伸びるまでゆっくり下ろします。"], []],
  ["x-chest-supported-machine-row", "Chest-Supported Machine Row", "チェストサポート・マシンロウ", ["middle-back"], ["lats", "biceps", "shoulders"], ["machine"], "h-pull", "c", 1, 2,
    ["Adjust the seat so the chest pad sits against your upper chest and your arms can fully extend.", "Grab the handles and sit tall.", "Pull the handles back, driving your elbows behind your torso and squeezing the shoulder blades.", "Return slowly to a full stretch."],
    ["胸パッドが上胸に当たり、腕が完全に伸びるようにシートを調整します。", "ハンドルを握り、背筋を伸ばして座ります。", "肘を体の後ろへ引き、肩甲骨を寄せながらハンドルを引きます。", "ゆっくりと完全に伸ばした位置まで戻します。"], []],
  ["x-cable-lateral-raise", "Cable Lateral Raise", "ケーブルサイドレイズ", ["shoulders"], [], ["cable"], "shoulder-raise", "i", 1, 1,
    ["Set a cable at the lowest position and stand side-on to the stack, holding the handle with the far hand.", "With a slight elbow bend, raise your arm out to the side until it is about shoulder height.", "Pause briefly, then lower slowly against the tension.", "Complete the reps and switch arms."],
    ["ケーブルを一番低い位置に設定し、マシンに対して横向きに立って遠い側の手でハンドルを持ちます。", "肘を軽く曲げたまま、腕を横に肩の高さまで上げます。", "一瞬止めてから、ケーブルの張力に耐えながらゆっくり下ろします。", "規定回数を終えたら反対の腕で行います。"], []],
  ["x-machine-lateral-raise", "Machine Lateral Raise", "マシンサイドレイズ", ["shoulders"], [], ["machine"], "shoulder-raise", "i", 1, 1,
    ["Adjust the seat so your shoulders line up with the machine's pivot.", "Place your forearms or hands on the pads and keep your back against the pad.", "Raise your arms out to the sides until about shoulder height.", "Lower slowly without letting the weight stack touch down."],
    ["肩がマシンの回転軸と同じ高さになるようにシートを調整します。", "前腕または手をパッドに当て、背中をシートにつけます。", "腕を横に肩の高さまで上げます。", "ウェイトが着地しないようゆっくり戻します。"], []],
  ["x-glute-extension-machine", "Glute Extension Machine", "グルートエクステンションマシン", ["glutes"], ["hamstrings"], ["machine"], "hinge", "i", 1, 2,
    ["Set the pad so it sits behind the working knee or under the foot, and hold the handles with your torso braced.", "Keep the hips square and the lower back neutral.", "Drive the leg back and up by squeezing the glute until the hip is fully extended.", "Lower slowly to a stretch without letting the weight stack touch down, then switch legs."],
    ["パッドが動かす脚の膝裏または足裏に当たるように調整し、ハンドルを握って体幹を固めます。", "骨盤を正面に向け、腰をニュートラルに保ちます。", "お尻を締めて、股関節が伸び切るまで脚を後ろ上方へ押し出します。", "ウェイトが着地しないようゆっくり伸ばした位置まで戻し、反対の脚も行います。"], []],
  ["x-hip-thrust-machine", "Hip Thrust Machine", "ヒップスラストマシン", ["glutes"], ["hamstrings", "quadriceps"], ["machine"], "hinge", "c", 1, 3,
    ["Sit with your upper back against the pad and the belt or lever resting across your hips.", "Plant your feet about hip-width apart, shins vertical at the top.", "Drive your hips up by squeezing the glutes until your torso is level.", "Lower with control and repeat without arching the lower back."],
    ["上背部をパッドにつけ、ベルトまたはレバーを腰に当てて座ります。", "足を腰幅に置き、トップですねが垂直になる位置にします。", "お尻を締めて腰を持ち上げ、上体が水平になるまで押し上げます。", "腰を反らさず、コントロールして下ろします。"], []],
  ["x-neutral-grip-lat-pulldown", "Neutral-Grip Lat Pulldown", "ニュートラルグリップ・ラットプルダウン", ["lats"], ["biceps", "middle-back"], ["cable"], "v-pull", "c", 1, 2,
    ["Sit with your thighs secured under the pad and hold the parallel-grip handle.", "Lean back slightly and pull your shoulder blades down.", "Pull the handle to your upper chest, driving your elbows down and back.", "Let the bar rise slowly until your arms are fully stretched."],
    ["太ももをパッドの下に固定して座り、パラレルグリップのハンドルを握ります。", "上体をわずかに後ろに倒し、肩甲骨を下げます。", "肘を下後方に引きながら、ハンドルを上胸まで引きます。", "腕が完全に伸びるまでゆっくり戻します。"], []],
  ["x-machine-row", "Seated Machine Row", "シーテッドマシンロウ", ["middle-back"], ["lats", "biceps"], ["machine"], "h-pull", "c", 1, 2,
    ["Sit with your chest against the pad and feet planted on the platform.", "Grip the handles with arms extended.", "Pull your elbows back, squeezing the shoulder blades together.", "Return slowly to a full stretch."],
    ["胸をパッドにつけ、足をステップに置いて座ります。", "腕を伸ばしてハンドルを握ります。", "肘を後ろへ引き、肩甲骨を寄せます。", "ゆっくりと完全に伸ばした位置まで戻します。"], []],
  ["x-landmine-press", "Landmine Press", "ランドマインプレス", ["shoulders"], ["chest", "triceps"], ["landmine", "barbell"], "v-press", "c", 1, 3,
    ["Wedge one end of a barbell in a corner or landmine base and hold the other end at shoulder height.", "Stand in a split stance with your ribs down.", "Press the end of the bar up and forward until your arm is straight.", "Lower under control to the shoulder."],
    ["バーベルの片端をコーナーまたはランドマインに固定し、もう一方の端を肩の高さで持ちます。", "足を前後に開いて立ち、肋骨を締めます。", "腕が伸びるまで、バーの先を上前方へ押します。", "コントロールして肩まで戻します。"], ["shoulder"]],
  ["x-landmine-row", "Landmine Row", "ランドマインロウ", ["middle-back"], ["lats", "biceps"], ["landmine", "barbell"], "h-pull", "c", 2, 3,
    ["Straddle the bar and hinge forward with a flat back, holding a handle or the bar end.", "Let the bar hang with your arms extended.", "Row the bar to your lower ribs, squeezing the shoulder blades.", "Lower slowly to full extension."],
    ["バーをまたいで背中を平らにし前傾します。ハンドルまたはバーの端を握ります。", "腕を伸ばしてバーを垂らします。", "肩甲骨を寄せながら、バーを下の肋骨まで引きます。", "ゆっくり完全に伸ばします。"], ["lower-back"]],
  ["x-landmine-squat", "Landmine Goblet Squat", "ランドマイン・ゴブレットスクワット", ["quadriceps"], ["glutes"], ["landmine", "barbell"], "squat", "c", 1, 3,
    ["Hold the end of the landmine bar against your chest with both hands.", "Stand with your feet shoulder-width apart.", "Squat down, keeping your chest tall and the bar close.", "Drive up through your feet to stand."],
    ["ランドマインバーの先端を両手で胸の前に抱えます。", "足を肩幅に開いて立ちます。", "胸を張り、バーを体に近づけたままスクワットします。", "足で床を押して立ち上がります。"], ["knee"]],
  ["x-single-arm-cable-row", "Single-Arm Cable Row", "ワンハンド・ケーブルロウ", ["middle-back"], ["lats", "biceps"], ["cable"], "h-pull", "c", 1, 2,
    ["Set a cable at chest height and hold the handle with one hand, stepping back until the cable is taut.", "Stand tall with a staggered stance.", "Row the handle to your ribs while keeping your torso still.", "Return slowly to a full stretch, then switch arms."],
    ["ケーブルを胸の高さに設定し、片手でハンドルを持ってケーブルが張るまで下がります。", "足を前後にずらして背筋を伸ばして立ちます。", "上体を動かさずに、ハンドルを肋骨まで引きます。", "ゆっくり完全に伸ばしたら、反対の腕に替えます。"], []],
  ["x-cable-pullover", "Cable Pullover", "ケーブルプルオーバー", ["lats"], ["chest", "triceps"], ["cable"], "v-pull", "i", 1, 2,
    ["Set a cable high and hold a straight bar or rope with arms extended overhead, facing the stack.", "Step back and hinge slightly at the hips.", "Keeping your arms nearly straight, sweep the bar down to your thighs.", "Return slowly to the overhead stretch."],
    ["ケーブルを高い位置に設定し、マシンに向かってバーまたはロープを頭上で握ります。", "一歩下がって、股関節をわずかに曲げます。", "腕をほぼ伸ばしたまま、バーを太ももへ弧を描いて引き下ろします。", "ゆっくり頭上のストレッチ位置に戻します。"], []],
  ["x-assisted-pullup-machine", "Assisted Pull-Up Machine", "アシストプルアップマシン", ["lats"], ["biceps", "middle-back"], ["machine"], "v-pull", "c", 1, 3,
    ["Choose the assist weight and kneel or stand on the platform.", "Grip the handles and pull your shoulder blades down.", "Pull your chest toward the handles until your chin passes them.", "Lower slowly to a full hang."],
    ["補助重量を選び、ステップに膝をつくか立ちます。", "ハンドルを握り、肩甲骨を下げます。", "あごがハンドルを越えるまで胸を引き上げます。", "ゆっくりとぶら下がった状態まで戻します。"], []],
  ["x-assisted-dip-machine", "Assisted Dip Machine", "アシストディップマシン", ["triceps"], ["chest", "shoulders"], ["machine"], "h-push", "c", 1, 3,
    ["Choose the assist weight and kneel on the pad.", "Grip the handles with straight arms.", "Lower until your upper arms are about parallel to the floor.", "Press back up to straight arms."],
    ["補助重量を選び、パッドに膝をつきます。", "腕を伸ばしてハンドルを握ります。", "上腕が床と平行になるまで下がります。", "腕が伸びるまで押し上げます。"], ["shoulder"]],
  ["x-nordic-curl", "Nordic Hamstring Curl", "ノルディックハムストリングカール", ["hamstrings"], ["glutes", "calves"], ["bodyweight"], "knee-flexion", "i", 3, 3,
    ["Kneel on a pad with your ankles anchored under a bar or held by a partner.", "Keep your body straight from knees to head.", "Lower your torso forward as slowly as you can, resisting with your hamstrings.", "Catch yourself with your hands and push back up."],
    ["パッドの上に膝をつき、足首をバーの下に固定するか、パートナーに押さえてもらいます。", "膝から頭まで体をまっすぐに保ちます。", "ハムストリングで耐えながら、できるだけゆっくり上体を前に倒します。", "手で体を受け止め、押して戻ります。"], ["knee"]],
  ["x-sissy-squat", "Sissy Squat", "シシースクワット", ["quadriceps"], [], ["bodyweight"], "squat", "i", 3, 2,
    ["Stand holding a support and rise onto your toes.", "Lean back while bending your knees forward, keeping a straight line from knees to shoulders.", "Lower as far as comfortable.", "Squeeze your quads to return to standing."],
    ["サポートにつかまって立ち、つま先立ちになります。", "膝を前に出しながら上体を後ろに倒し、膝から肩まで一直線に保ちます。", "無理のない範囲まで下がります。", "大腿四頭筋に力を入れて立ち上がります。"], ["knee"]],
  ["x-tibialis-raise", "Tibialis Raise", "ティビアリスレイズ", ["calves"], [], ["bodyweight"], "calf", "i", 1, 1,
    ["Lean your back against a wall with your feet a step or two in front of you.", "Keeping your heels on the floor, pull your toes up toward your shins.", "Pause at the top, then lower slowly."],
    ["壁に背中をつけ、足を一、二歩前に出します。", "かかとを床につけたまま、つま先をすねに向けて引き上げます。", "トップで止めてから、ゆっくり戻します。"], []],
  ["x-bayesian-curl", "Bayesian Cable Curl", "ベイジアン・ケーブルカール", ["biceps"], ["forearms"], ["cable"], "elbow-flexion", "i", 1, 1,
    ["Set a cable low and face away from the stack, holding the handle behind you with your arm extended.", "Step forward to create tension and keep your upper arm slightly behind your torso.", "Curl the handle up without moving the elbow forward.", "Lower slowly to a full stretch."],
    ["ケーブルを低い位置に設定し、マシンに背を向けて、腕を後ろに伸ばしてハンドルを持ちます。", "一歩前に出して張力をかけ、上腕を体の少し後ろに保ちます。", "肘を前に出さずにハンドルを巻き上げます。", "ゆっくり完全に伸ばします。"], []],
  ["x-dead-hang", "Dead Hang", "デッドハング", ["forearms"], ["lats", "shoulders"], ["pullup-bar"], "grip", "i", 1, 1,
    ["Grip a pull-up bar slightly wider than shoulder width.", "Hang with arms straight and shoulders gently engaged.", "Hold for time, breathing steadily."],
    ["肩幅よりやや広くバーを握ります。", "腕を伸ばし、肩を軽く引き下げてぶら下がります。", "呼吸を保ちながら時間いっぱい耐えます。"], []],
  ["x-hanging-knee-raise", "Hanging Knee Raise", "ハンギングニーレイズ", ["abdominals"], ["forearms"], ["pullup-bar"], "core", "i", 1, 1,
    ["Hang from a pull-up bar with arms straight.", "Curl your pelvis up and bring your knees toward your chest.", "Lower slowly without swinging."],
    ["腕を伸ばしてバーにぶら下がります。", "骨盤を巻き上げ、膝を胸に引き寄せます。", "反動を使わずゆっくり下ろします。"], []],
  ["x-copenhagen-plank", "Copenhagen Plank", "コペンハーゲンプランク", ["adductors"], ["abdominals"], ["bench"], "hip-abduction", "i", 2, 2,
    ["Lie on your side with your top leg resting on a bench and your forearm on the floor.", "Lift your hips so your body forms a straight line.", "Hold, then switch sides."],
    ["横向きに寝て、上の脚をベンチに乗せ、前腕を床につきます。", "腰を持ち上げ、体を一直線にします。", "保持したら、反対側に替えます。"], []],
  ["x-side-plank", "Side Plank", "サイドプランク", ["abdominals"], ["glutes"], ["bodyweight"], "core", "i", 1, 1,
    ["Lie on your side with your forearm under your shoulder.", "Lift your hips so your body forms a straight line.", "Hold, then switch sides."],
    ["横向きに寝て、肩の真下に前腕をつきます。", "腰を持ち上げ、体を一直線にします。", "保持したら、反対側に替えます。"], []],
  ["x-bird-dog", "Bird Dog", "バードドッグ", ["lower-back"], ["glutes", "abdominals"], ["bodyweight"], "core", "i", 1, 1,
    ["Start on hands and knees with a flat back.", "Extend one arm forward and the opposite leg back at the same time.", "Pause without rotating the hips, then return and switch sides."],
    ["四つ這いになり、背中を平らにします。", "片腕と反対側の脚を同時に伸ばします。", "骨盤を回さずに止め、戻して反対側に替えます。"], []],
  ["x-bodyweight-glute-bridge", "Glute Bridge", "グルートブリッジ", ["glutes"], ["hamstrings"], ["bodyweight"], "hinge", "c", 1, 1,
    ["Lie on your back with knees bent and feet flat.", "Drive through your heels and lift your hips until your body is a straight line.", "Squeeze your glutes at the top, then lower."],
    ["仰向けで膝を曲げ、足裏を床につけます。", "かかとで床を押し、体が一直線になるまで腰を持ち上げます。", "トップでお尻を締めてから下ろします。"], []],
  ["x-band-face-pull", "Band Face Pull", "バンドフェイスプル", ["shoulders"], ["middle-back", "traps"], ["bands"], "fly", "c", 1, 1,
    ["Anchor a band at head height and hold the ends with both hands, stepping back for tension.", "Pull the band toward your face, elbows high and wide.", "Squeeze your rear delts, then return slowly."],
    ["バンドを頭の高さに固定し、両手で持って張るまで下がります。", "肘を高く外に開きながら、バンドを顔に向けて引きます。", "後部三角筋を締め、ゆっくり戻します。"], []],
  ["x-band-curl", "Band Biceps Curl", "バンドカール", ["biceps"], [], ["bands"], "elbow-flexion", "i", 1, 1,
    ["Stand on the middle of a band and hold the ends with palms up.", "Curl your hands toward your shoulders, keeping your elbows at your sides.", "Lower slowly against the tension."],
    ["バンドの中央を踏み、両端を手のひらを上にして持ちます。", "肘を体の脇に固定し、手を肩に向けて巻き上げます。", "張力に耐えながらゆっくり下ろします。"], []],
  ["x-band-pushdown", "Band Triceps Pushdown", "バンド・トライセプスプッシュダウン", ["triceps"], [], ["bands"], "elbow-extension", "i", 1, 1,
    ["Anchor a band overhead and hold the ends with elbows at your sides.", "Press your hands down until your arms are straight.", "Return slowly until your forearms are just past parallel."],
    ["バンドを頭上に固定し、肘を体の脇につけて両端を持ちます。", "腕が伸びるまで手を押し下げます。", "前腕が水平を少し越えるまでゆっくり戻します。"], ["elbow"]],
  ["x-band-row", "Band Row", "バンドロウ", ["middle-back"], ["lats", "biceps"], ["bands"], "h-pull", "c", 1, 1,
    ["Sit with legs extended and loop a band around your feet, holding the ends.", "Sit tall and pull your hands to your ribs, squeezing the shoulder blades.", "Return slowly with control."],
    ["脚を伸ばして座り、足にバンドを掛けて両端を持ちます。", "背筋を伸ばし、肩甲骨を寄せながら手を肋骨まで引きます。", "コントロールしてゆっくり戻します。"], []],
  ["x-band-chest-press", "Band Chest Press", "バンドチェストプレス", ["chest"], ["triceps", "shoulders"], ["bands"], "h-push", "c", 1, 1,
    ["Wrap a band behind your upper back and hold the ends at chest level.", "Press your hands forward until your arms are straight.", "Return slowly until your elbows are slightly behind the torso."],
    ["バンドを上背部に回し、両端を胸の高さで持ちます。", "腕が伸びるまで手を前に押し出します。", "肘が体の少し後ろに来るまでゆっくり戻します。"], ["shoulder"]],
  ["x-band-squat", "Band Squat", "バンドスクワット", ["quadriceps"], ["glutes"], ["bands"], "squat", "c", 1, 2,
    ["Stand on a band with feet shoulder-width apart and hold the other end at your shoulders.", "Squat down with your chest tall.", "Stand up against the band tension."],
    ["足を肩幅に開いてバンドを踏み、もう一端を肩の前で持ちます。", "胸を張ってしゃがみます。", "バンドの張力に抗して立ち上がります。"], ["knee"]],
  ["x-trx-biceps-curl", "Suspension Biceps Curl", "サスペンション・バイセップスカール", ["biceps"], [], ["trx"], "elbow-flexion", "i", 1, 1,
    ["Hold the straps with palms up and lean back with arms extended.", "Curl your hands toward your head, keeping your elbows high.", "Lower slowly to full extension."],
    ["手のひらを上にしてストラップを握り、腕を伸ばして後ろに傾きます。", "肘を高く保ち、手を頭に向けて曲げます。", "ゆっくり完全に伸ばします。"], []],
  ["x-trx-triceps-extension", "Suspension Triceps Extension", "サスペンション・トライセプスエクステンション", ["triceps"], ["shoulders"], ["trx"], "elbow-extension", "i", 2, 2,
    ["Hold the straps at head height and lean forward in a plank-like line.", "Bend your elbows to lower your head between your hands.", "Extend your elbows to return."],
    ["ストラップを頭の高さで握り、プランクのように前傾します。", "肘を曲げて、頭を両手の間に下げます。", "肘を伸ばして戻ります。"], ["elbow"]],
  ["x-trx-face-pull", "Suspension Face Pull", "サスペンション・フェイスプル", ["shoulders"], ["middle-back", "traps"], ["trx"], "fly", "c", 1, 1,
    ["Hold the straps with palms down and lean back with arms extended.", "Pull your hands toward your face, elbows high and wide.", "Lower slowly."],
    ["手のひらを下にしてストラップを握り、腕を伸ばして後ろに傾きます。", "肘を高く外に開き、手を顔に向けて引きます。", "ゆっくり戻します。"], []],
  ["x-trx-chest-fly", "Suspension Chest Fly", "サスペンション・チェストフライ", ["chest"], ["shoulders"], ["trx"], "fly", "i", 2, 2,
    ["Hold the straps with arms out wide and lean forward on your toes.", "Bring your hands together in front of your chest, keeping a slight elbow bend.", "Open slowly to a comfortable stretch."],
    ["腕を横に広げてストラップを握り、つま先で前傾します。", "肘を軽く曲げたまま、胸の前で手を合わせます。", "無理のない範囲までゆっくり開きます。"], ["shoulder"]],
  ["x-trx-hamstring-curl", "Suspension Hamstring Curl", "サスペンション・ハムストリングカール", ["hamstrings"], ["glutes"], ["trx"], "knee-flexion", "i", 2, 2,
    ["Lie on your back with your heels in the straps and hips lifted.", "Curl your heels toward your glutes while keeping your hips up.", "Extend slowly without dropping the hips."],
    ["仰向けでかかとをストラップに入れ、腰を持ち上げます。", "腰を保ったまま、かかとをお尻に引き寄せます。", "腰を落とさずゆっくり伸ばします。"], []],
  ["x-smith-hip-thrust", "Smith Machine Hip Thrust", "スミスマシン・ヒップスラスト", ["glutes"], ["hamstrings"], ["smith", "bench"], "hinge", "c", 2, 3,
    ["Sit with your upper back against a bench and the bar padded across your hips.", "Plant your feet so shins are vertical at the top.", "Drive your hips up, squeezing the glutes.", "Lower with control."],
    ["上背部をベンチにつけ、パッドを巻いたバーを腰に当てて座ります。", "トップですねが垂直になる位置に足を置きます。", "お尻を締めて腰を押し上げます。", "コントロールして下ろします。"], []],
  ["x-kettlebell-swing", "Kettlebell Swing", "ケトルベルスイング", ["glutes"], ["hamstrings", "lower-back"], ["kettlebell"], "hinge", "c", 2, 3,
    ["Stand with feet shoulder-width apart and the kettlebell on the floor in front of you.", "Hinge back, hike the bell between your legs, then snap your hips forward.", "Let the bell float to chest height with straight arms.", "Let it fall back and hinge into the next rep."],
    ["足を肩幅に開き、ケトルベルを体の前の床に置きます。", "股関節を引き、ベルを脚の間に振り込み、腰を前に鋭く押し出します。", "腕を伸ばしたまま、ベルを胸の高さまで浮かせます。", "ベルが落ちてくるのに合わせて、次の回へ股関節を引きます。"], ["lower-back"]],
  ["x-kettlebell-deadlift", "Kettlebell Deadlift", "ケトルベルデッドリフト", ["glutes"], ["hamstrings", "quadriceps"], ["kettlebell"], "hinge", "c", 1, 3,
    ["Stand with the kettlebell between your feet and hinge back to grip it.", "Keep a flat back and chest up.", "Push through the floor and stand tall, squeezing the glutes.", "Lower by hinging back."],
    ["足の間にケトルベルを置き、股関節を引いて握ります。", "背中を平らにして胸を張ります。", "床を押して立ち上がり、お尻を締めます。", "股関節を引いて下ろします。"], ["lower-back"]],
  ["x-kettlebell-row", "Kettlebell Gorilla Row", "ケトルベル・ゴリラロウ", ["middle-back"], ["lats", "biceps"], ["kettlebell"], "h-pull", "c", 2, 3,
    ["Place two kettlebells on the floor between your feet and hinge over to grip them.", "Row one bell to your ribs while the other stays down.", "Lower it and repeat on the other side."],
    ["足の間に2つのケトルベルを置き、前傾して握ります。", "片方のベルを肋骨まで引き、もう一方は床に置いたままにします。", "下ろして反対側も同様に行います。"], ["lower-back"]],
  ["x-neutral-grip-db-press", "Neutral-Grip Seated Dumbbell Press", "ニュートラルグリップ・シーテッドダンベルプレス", ["shoulders"], ["triceps"], ["dumbbell", "bench"], "v-press", "c", 1, 3,
    ["Sit on an upright bench with dumbbells at shoulder height, palms facing each other.", "Press the dumbbells overhead until your arms are straight.", "Lower slowly back to shoulder height."],
    ["背もたれを立てたベンチに座り、手のひらを向かい合わせてダンベルを肩の高さで構えます。", "腕が伸びるまでダンベルを頭上に押し上げます。", "ゆっくり肩の高さまで戻します。"], ["shoulder"]],
  ["x-machine-chest-fly", "Machine Chest Fly", "マシンチェストフライ", ["chest"], ["shoulders"], ["machine"], "fly", "i", 1, 2,
    ["Adjust the seat so the handles are at chest height.", "Bring the handles together in front of your chest.", "Return slowly until you feel a comfortable chest stretch."],
    ["ハンドルが胸の高さになるようにシートを調整します。", "胸の前でハンドルを合わせます。", "胸が心地よく伸びる位置までゆっくり戻します。"], ["shoulder"]],
  ["x-incline-machine-press", "Incline Machine Press", "インクラインマシンプレス", ["chest"], ["shoulders", "triceps"], ["machine"], "h-push", "c", 1, 2,
    ["Adjust the seat so the handles line up with your upper chest.", "Press the handles forward and up until your arms are straight.", "Lower slowly until you feel a stretch in the chest."],
    ["ハンドルが上胸の高さになるようにシートを調整します。", "腕が伸びるまでハンドルを前上方に押します。", "胸が伸びるところまでゆっくり戻します。"], ["shoulder"]],
  ["x-hip-abduction-band", "Banded Hip Abduction", "バンド・ヒップアブダクション", ["abductors"], ["glutes"], ["bands"], "hip-abduction", "i", 1, 1,
    ["Place a loop band above your knees and sit or stand tall.", "Push your knees apart against the band.", "Return slowly."],
    ["膝の上にループバンドをかけ、背筋を伸ばして座るか立ちます。", "バンドに逆らって膝を外に開きます。", "ゆっくり戻します。"], []],
  ["x-reverse-lunge", "Dumbbell Reverse Lunge", "ダンベル・リバースランジ", ["quadriceps"], ["glutes", "hamstrings"], ["dumbbell"], "lunge", "c", 1, 3,
    ["Stand holding dumbbells at your sides.", "Step one foot back and lower until both knees are about 90 degrees.", "Push through the front foot to return to standing, then alternate legs."],
    ["ダンベルを両手に持って立ちます。", "片足を後ろに引き、両膝が約90度になるまで下ります。", "前足で床を押して立ち上がり、左右交互に行います。"], ["knee"]],
  ["x-walking-lunge-db", "Dumbbell Walking Lunge", "ダンベル・ウォーキングランジ", ["quadriceps"], ["glutes", "hamstrings"], ["dumbbell"], "lunge", "c", 1, 4,
    ["Hold dumbbells at your sides and take a long step forward.", "Lower until both knees are about 90 degrees.", "Push off the front foot and step through into the next lunge."],
    ["ダンベルを両手に持ち、大きく一歩前に踏み出します。", "両膝が約90度になるまで下ります。", "前足で蹴って、次のランジへ踏み出します。"], ["knee"]],
  ["x-pec-dec-rear-delt", "Rear Delt Machine Fly", "リアデルトマシンフライ", ["shoulders"], ["middle-back", "traps"], ["machine"], "fly", "i", 1, 1,
    ["Sit facing the pad with the handles at shoulder height.", "With arms nearly straight, sweep the handles out and back.", "Squeeze the rear delts, then return slowly."],
    ["パッドに向かって座り、ハンドルを肩の高さに合わせます。", "腕をほぼ伸ばしたまま、ハンドルを外後方に開きます。", "後部三角筋を締め、ゆっくり戻します。"], []],
  ["x-ez-bar-overhead-extension", "EZ-Bar Overhead Triceps Extension", "EZバー・オーバーヘッドトライセプスエクステンション", ["triceps"], [], ["ez-bar", "bench"], "elbow-extension", "i", 2, 2,
    ["Sit or stand holding an EZ bar overhead with a narrow grip.", "Bend your elbows to lower the bar behind your head.", "Extend your elbows to press the bar back overhead."],
    ["EZバーをナローグリップで頭上に持ち、座るか立ちます。", "肘を曲げてバーを頭の後ろに下ろします。", "肘を伸ばしてバーを頭上へ戻します。"], ["elbow"]],
  ["x-cable-woodchop-low-high", "Low-to-High Cable Chop", "ロー・トゥ・ハイ・ケーブルチョップ", ["abdominals"], ["shoulders"], ["cable"], "rotation", "c", 1, 2,
    ["Set a cable low and stand side-on, holding the handle with both hands.", "Rotate your torso and lift the handle diagonally across your body.", "Return slowly, then switch sides."],
    ["ケーブルを低い位置に設定し、横向きに立って両手でハンドルを持ちます。", "体幹を回しながら、ハンドルを斜め上へ引き上げます。", "ゆっくり戻したら、反対側に替えます。"], []],
  ["x-farmers-carry-db", "Dumbbell Farmer's Carry", "ダンベル・ファーマーズキャリー", ["forearms"], ["traps", "abdominals"], ["dumbbell"], "carry", "c", 1, 3,
    ["Pick up a heavy dumbbell in each hand and stand tall.", "Walk with short, controlled steps for distance or time.", "Keep your ribs down and shoulders level."],
    ["重いダンベルを両手に持ち、背筋を伸ばして立ちます。", "小さくコントロールされた歩幅で、距離または時間を決めて歩きます。", "肋骨を締め、肩の高さを水平に保ちます。"], []],
  ["x-shrug-machine", "Machine Shrug", "マシンシュラッグ", ["traps"], [], ["machine"], "shrug", "i", 1, 1,
    ["Sit or stand with the handles at your sides.", "Lift your shoulders straight up toward your ears.", "Pause, then lower slowly."],
    ["ハンドルを体の脇で持ち、座るか立ちます。", "肩を耳に向けてまっすぐ持ち上げます。", "一瞬止めて、ゆっくり下ろします。"], []],
  ["x-pushup-bw", "Standard Push-Up", "スタンダード・プッシュアップ", ["chest"], ["triceps", "shoulders"], ["bodyweight"], "h-push", "c", 1, 2,
    ["Place your hands slightly wider than shoulders and form a straight line from head to heels.", "Lower your chest toward the floor with elbows about 45 degrees from your torso.", "Press back up to straight arms."],
    ["手を肩幅よりやや広くつき、頭からかかとまで一直線にします。", "肘を体から約45度に保ち、胸を床に近づけます。", "腕が伸びるまで押し上げます。"], ["wrist"]],
  ["x-leg-press-calf-raise", "Seated Leg Press Calf Press", "レッグプレスでのカーフプレス（座位）", ["calves"], [], ["machine"], "calf", "i", 1, 1,
    ["Sit in the leg press and place the balls of your feet on the lower edge of the platform with legs straight.", "Press through your toes to extend your ankles.", "Lower slowly for a deep stretch."],
    ["レッグプレスに座り、脚を伸ばしてプレートの下端につま先を乗せます。", "つま先で押して足首を伸ばします。", "ゆっくり戻して深くストレッチします。"], []],
  ["x-cable-crunch-kneel", "Kneeling Rope Cable Crunch", "ニーリング・ロープケーブルクランチ", ["abdominals"], [], ["cable"], "core", "i", 1, 1,
    ["Kneel facing a high cable and hold the rope beside your head.", "Curl your ribs toward your pelvis, bringing your elbows toward your knees.", "Return slowly without letting your hips move."],
    ["ハイケーブルに向かって膝立ちし、ロープを頭の横で持ちます。", "肋骨を骨盤に近づけるように丸め、肘を膝に向けます。", "腰を動かさずにゆっくり戻します。"], []],
  ["x-cable-curl-straight", "Cable Biceps Curl", "ケーブルカール", ["biceps"], ["forearms"], ["cable"], "elbow-flexion", "i", 1, 1,
    ["Stand facing a low cable and hold a straight bar with palms up.", "Curl the bar toward your shoulders, keeping your elbows at your sides.", "Lower slowly until your arms are straight."],
    ["ローケーブルに向かって立ち、ストレートバーを手のひらを上にして握ります。", "肘を体の脇に固定し、バーを肩に向けて巻き上げます。", "腕が伸びるまでゆっくり下ろします。"], []],
  ["x-overhead-cable-extension", "Overhead Cable Triceps Extension", "オーバーヘッド・ケーブルトライセプスエクステンション", ["triceps"], [], ["cable"], "elbow-extension", "i", 1, 1,
    ["Face away from a cable set at the middle height and hold the rope behind your head.", "Step forward and lean slightly, elbows pointing up.", "Extend your elbows until your arms are straight overhead.", "Return slowly to a deep stretch."],
    ["ミドルの高さに設定したケーブルに背を向け、ロープを頭の後ろで持ちます。", "一歩前に出て軽く前傾し、肘を上に向けます。", "腕が頭上でまっすぐになるまで肘を伸ばします。", "ゆっくり深いストレッチ位置まで戻します。"], ["elbow"]],
  ["x-bench-supported-db-fly-rear", "Chest-Supported Rear Delt Raise", "チェストサポート・リアデルトレイズ", ["shoulders"], ["middle-back", "traps"], ["dumbbell", "bench"], "fly", "i", 1, 1,
    ["Lie face down on an incline bench with a dumbbell in each hand.", "With a slight elbow bend, raise your arms out to the sides.", "Squeeze your rear delts, then lower slowly."],
    ["インクラインベンチにうつ伏せになり、ダンベルを両手に持ちます。", "肘を軽く曲げたまま、腕を横に持ち上げます。", "後部三角筋を締め、ゆっくり下ろします。"], []],
  ["x-pause-squat", "Pause Squat", "ポーズスクワット", ["quadriceps"], ["glutes", "lower-back"], ["barbell"], "squat", "c", 3, 5,
    ["Set the bar on your upper back and squat down under control.", "Pause for one to two seconds at the bottom without relaxing.", "Drive up powerfully to standing."],
    ["バーを上背部に担ぎ、コントロールしてしゃがみます。", "ボトムで力を抜かずに1〜2秒止めます。", "力強く立ち上がります。"], ["knee", "lower-back"]],
  ["x-dumbbell-pullover-bench", "Cross-Bench Dumbbell Pullover", "クロスベンチ・ダンベルプルオーバー", ["lats"], ["chest", "triceps"], ["dumbbell", "bench"], "v-pull", "i", 2, 2,
    ["Lie across a bench with only your upper back supported and hold one dumbbell overhead with both hands.", "Lower the dumbbell behind your head with a slight elbow bend.", "Pull it back over your chest, squeezing your lats."],
    ["上背部だけがベンチに乗るように横向きに寝て、ダンベルを両手で頭上に持ちます。", "肘を軽く曲げたまま、ダンベルを頭の後ろに下ろします。", "広背筋を意識して、ダンベルを胸の上まで引き戻します。"], ["shoulder"]],
];

export const EXTRAS = rows.map(([id, n, j, p, s, e, pat, m, d, f, en, ja, jt]) => ({
  meta: { id, n, j, p, s, e, pat, m, d, f, jt },
  en,
  ja,
}));
